version: '3.4'
services:
  hulaf:
    build: './HULAF.FrontEnd'
    image: 'hulaf'
    ports: 
      # - 80:80
      # - 443:443
      - 8080:8080
    environment: 
      - ENV=dev
  hulafapi:
    build: './HULAF.BackEnd'
    image: 'hulafapi'
    # ports:
    #   - 5000:5000
    environment: 
      - ASPNETCORE_ENVIRONMENT=dev
      - ASPNETCORE_URLS=http://hulafapi:5000