openapi: '3.0.0'

info:
  title: HULAF Persons controller
  description: Retrieves persons from database
  version: 0.0.0

paths:
  $ref: './paths.yaml'
  
components:
  $ref: './components/schemas.yaml'