openapi: '3.0.0'

info:
  title: HULAF Location controller
  description: Retrieves a location from database
  version: 0.0.0

# paths:
#   $ref: './paths.yaml'
  
components:
  $ref: './components/schemas.yaml'