openapi: 3.0.0
info:
  title: HULAF Persons controller
  description: Retrieves persons from database
  version: 0.0.0
paths:
  /missingperson:
    get:
      summary: Returns a missing person
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                $ref: '#/definitions/MissingPersonDto'
  /seekerperson:
    get:
      summary: A person seeks a missing person
      description: null
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                $ref: '#/definitions/SeekerPersonDto'
definitions:
  MissingPersonDto:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
  SeekerPersonDto:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

