openapi: 3.0.0
info:
  title: HULAF Persons controller
  description: Retrieves persons from database
  version: 0.0.0
paths:
  '/missingperson/{personGuid}':
    get:
      tags:
        - person
        - missing
      description: Returns a missing person
      summary: Gets a missing person by guid.
      operationId: getMissingPerson
      responses:
        '200':
          description: Returns a missing person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MissingPersonDto'
      parameters:
        - name: personGuid
          in: path
          description: Guid of person
          required: true
          schema:
            type: string
  /missingpersonlist:
    get:
      tags:
        - person
        - missing
      description: Returns a missing person list
      summary: Lists missing persons
      operationId: getMissingPersonList
      responses:
        '200':
          description: Missing person list.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MissingPersonDto'
  /seekerperson:
    get:
      description: Returns a person looking for a missing person
      summary: A person seeks a missing person
      responses:
        '200':
          description: Get a person by guid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeekerPersonDto'
components:
  schemas:
    MissingPersonDto:
      type: object
      properties:
        guid:
          type: string
          fromat: uuid
        name:
          type: string
        characteristics:
          type:
            $ref: '#/comonents/schemas/CharacteristicsDto'
    SeekerPersonDto:
      type: object
      properties:
        guid:
          type: string
          fromat: uuid
        name:
          type: string
    CharateristicsDto:
      type: object
      properties:
        guid:
          type: string
          fromat: uuid
        approxHeightMin:
          type: integer
          example: Height in cm
        approxHeightMax:
          type: integer
          example: Height in cm
        hairColor:
          type:
            $ref: '#/components/schemas/HairColorDto'
        eyeColor:
          type:
            $ref: '#/components/schemas/EyeColorDto'
        approxAgeMin:
          type: integer
        approxAgeMax:
          type: integer
        knownNames:
          type: array
          items:
            type: string
    EyeColorDto:
      type: string
      enum:
        - green
        - blue
    HairColorDto:
      type: string
      enum:
        - brown
        - blonde

