openapi: 3.0.0
info:
  title: HULAF Persons controller
  description: Retrieves persons from database
  version: 0.0.0
paths:
  '/person/missingperson/{personGuid}':
    get:
      tags:
        - person
        - missing
      description: Returns a missing person
      summary: Gets a missing person by guid.
      operationId: getMissingPerson
      parameters:
        - name: personGuid
          in: path
          description: Guid of person
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Returns a missing person
          content:
            application/json:
              schema:
                description: A missing person
                $ref: '#/components/schemas/MissingPersonDto'
  /person/missingpersonlist:
    get:
      tags:
        - person
        - missing
      description: Returns a missing person list
      summary: Lists missing persons
      operationId: getMissingPersonList
      responses:
        '200':
          description: Missing person list.
          content:
            '*/*':
              schema:
                type: array
                items:
                  description: A missing person
                  $ref: '#/components/schemas/MissingPersonDto'
  '/person/seekerperson/{personGuid}':
    get:
      tags:
        - person
        - seeking
      description: Returns a person looking for a missing person
      summary: A person seeks a missing person
      operationId: getSeekerPerson
      parameters:
        - name: personGuid
          in: path
          description: Guid of person
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Get a person by guid
          content:
            application/json:
              schema:
                description: A person looking form someone missing
                $ref: '#/components/schemas/SeekerPersonDto'
  /location/countrylist:
    get:
      tags:
        - location
        - list
      description: Returns a list of countries
      summary: Lists countries
      operationId: getCountryList
      responses:
        '200':
          description: Country list.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryDto'
components:
  schemas:
    MissingPersonDto:
      description: A missing person
      allOf:
        - $ref: '#/components/schemas/PersonDto'
        - type: object
          properties:
            lastSeenLocations:
              type: array
              items:
                $ref: '#/components/schemas/LocationDto'
    PersonDto:
      type: object
      discriminator:
        propertyName: personType
      required:
        - guid
        - personType
      properties:
        guid:
          type: string
          format: uuid
        personType:
          type: string
        characteristics:
          $ref: '#/components/schemas/CharacteristicsDto'
        contactInfo:
          $ref: '#/components/schemas/ContactInfoDto'
    SeekerPersonDto:
      description: A person looking form someone missing
      allOf:
        - $ref: '#/components/schemas/PersonDto'
        - type: object
          properties:
            locationsOfSearch:
              type: array
              items:
                $ref: '#/components/schemas/LocationDto'
    CharacteristicsDto:
      type: object
      properties:
        guid:
          type: string
          fromat: uuid
        approxHeightMin:
          type: integer
          example: Height in cm
        approxHeightMax:
          type: integer
          example: Height in cm
        hairColor:
          $ref: '#/components/schemas/HairColorDto'
        eyeColor:
          $ref: '#/components/schemas/EyeColorDto'
        approxAgeMin:
          type: integer
        approxAgeMax:
          type: integer
        knownNames:
          type: array
          items:
            type: string
    EyeColorDto:
      type: string
      enum:
        - green
        - blue
    HairColorDto:
      type: string
      enum:
        - brown
        - blonde
    ContactInfoDto:
      type: object
      properties:
        guid:
          type: string
          fromat: uuid
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          fromat: email
    CityDto:
      type: object
      properties:
        guid:
          type: string
          format: uuid
        name:
          type: string
    CoordinatesDto:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
      required:
        - lat
        - lng
    CountryDto:
      type: object
      properties:
        guid:
          type: string
          format: uuid
        name:
          type: string
        dialingCode:
          type: integer
    LocationDto:
      type: object
      properties:
        country:
          $ref: '#/components/schemas/CountryDto'
        city:
          $ref: '#/components/schemas/CityDto'
        coordinates:
          $ref: '#/components/schemas/CoordinatesDto'
