openapi: 3.0.0
info:
  title: HULAF Location controller
  description: Retrieves a location from database
  version: 0.0.0
paths:
  /get-country-list:
    get:
      tags:
        - location
        - list
      description: Returns a list of countries
      summary: Lists countries
      operationId: getCountryList
      responses:
        '200':
          description: Country list.
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryDto'
components:
  schemas:
    CityDto:
      type: object
      properties:
        Guid:
          type: string
          format: uuid
        Name:
          type: string
        Country:
          type: object
          properties:
            Guid:
              type: string
              format: uuid
            Name:
              type: string
            DialingCode:
              type: integer
    CoordinatesDto:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number
    CountryDto:
      type: object
      properties:
        Guid:
          type: string
          format: uuid
        Name:
          type: string
        DialingCode:
          type: integer
    LocationDto:
      type: object
      properties:
        country:
          $ref: '#/components/schemas/CountryDto'
        city:
          $ref: '#/components/schemas/CityDto'
        coordinates:
          $ref: '#/components/schemas/CoordinatesDto'
